# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

r_binary_packages: 
  - rjags 
  - r2jags

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - jags_install  


env:
 global:
   - NOT_CRAN=true
   - R_BUILD_ARGS="--no-manual "
   - R_CHECK_ARGS="--no-manual --as-cran "

apt_packages:
  - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change
    
