language: r
warnings_are_errors: true
sudo: required

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags 

env:
 global:
   - CRAN: http://cran.rstudio.com
   - WARNINGS_ARE_ERRORS=1
   - R_BUILD_ARGS=--no-manual 
   - R_CHECK_ARGS=--no-manual --as-cran 
   
apt_packages:
  - libv8-dev

r_packages:
  - rjags

notifications:
  email:
    on_success: change
    on_failure: change
  
