# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

allow_failures:
  - os: osx

r_binary_packages: 
  - R2jags

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - jags_install || true
  - export PROJ_DIR=`basename ${TRAVIS_BUILD_DIR}`
  - export PACKAGE_NAME=`package_name`

script:
  - echo "Overriding travis R script"

jobs:
  include:
    - script:
      - cd ..
      - travis_wait 100 R CMD build ${PROJ_DIR} ${R_BUILD_ARGS}
      - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
      - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}";
      os: linux
    - script:
      - cd ..
      - travis_wait 100 R CMD build ${PROJ_DIR} ${R_BUILD_ARGS}
      - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
      - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}";
      os: osx
  
env:
 global:
  - NOT_CRAN=TRUE
  - RGL_USE_NULL=TRUE
  - R_BUILD_ARGS=" --no-manual"
  - R_CHECK_ARGS=" --timings --as-cran --no-manual"

notifications:
  email:
    on_success: change
    on_failure: change
    
