# Sample .travis.yml for R projects

language: r
language: c
sudo: required
warnings_are_errors: true
#env:
#  global:
#    - NOT_CRAN=true
#before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://raw.github.com/lcolladotor/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
 
install:
  - ./travis-tool.sh install_deps
  
notifications:
  email:
    on_success: change
    on_failure: change
